### ISSUE TITLE
Internal ordering of data

### ISSUE THREAD

**Issue by InfiniteRegression** [libmir/mir-algorithm#101]
The dimensions of ndslice seem to be fixed regardless of what I am assigning.

```d
	import mir.ndslice;

	auto matrix = slice!double(5, 2);
	matrix[] = 0;

	for(int j = 0; j < matrix.length!1; j++)
		for(int i = 0; i < matrix.length!0; i++)
			matrix[i,j] = matrix.length!0*j + i;
```
but, similarly,
```d
	import mir.ndslice;

	auto matrix = slice!double(2, 5);
	matrix[] = 0;


	for(int j = 0; j < matrix.length!1; j++)
		for(int i = 0; i < matrix.length!0; i++)
			matrix[j,i] = matrix.length!0*j + i;
```
but both seem to identically write the matrix by skipping around rather than sequentially, which is better for larger datasets.

e.g., both write this way:

00000000 00000005 00000001 00000006 00000002 00000007 00000003 00000008 00000004 00000009

rather than sequentially, even though it should be sequential. Of course, one can't swap the dimensions and keep the same indexing as this results in an error.

Does mir do this intentionally and not worried about cache misses or is it a bug?

auto matrix = slice!double(2, 5);

is a 2 row by 5 column matrix, correct? Regardless, Should it not store the rows sequentially.

BTW, the point is not to write the correct squence to memory but to demonstrate how ndslice writes a sequential list of bytes to memory, in which case it "shuffles" them up. That is, it transposes the memory layout in to an sub-optimal form.

**Comment by 9il** [comment]
Have you run you examples in debug mode (without -O -inline -release)?

The second one fails because it is wrong. 
```
core.exception.AssertError: index at position 0LU from the range [0 ..2LU) must be less than corresponding length.
```
It can be translated as: `j` should be less then `matrix.length!0` (2), but you iterates until `matrix.length!1` (5).

So, the bug is in you code.

Rows  are located consequently in memory one-by-one in single contiguous memory chunk (after allocation and always for Contiguous slices).

Possibly you wanted to write:
```d
	auto matrix = slice!double(2, 5);
	matrix[] = 0;

	for(int j = 0; j < matrix.length!0; j++)
		for(int i = 0; i < matrix.length!1; i++)
			matrix[j, i] = matrix.length!0*j + i;

    import std.stdio;
    writeln(matrix);  // prints [[0, 1, 2, 3, 4], [2, 3, 4, 5, 6]]
```
The documentaion http://docs.algorithm.dlang.io/latest/mir_ndslice_slice.html#.Slice contains section _Internal Binary Representation_. It is for universal slices; canonical and contiguous slices just have more constrains on dimension permutation.

**Comment by 9il** [comment]
> writeln(matrix);  // prints [[0, 1, 2, 3, 4], [2, 3, 4, 5, 6]]

Oh, probably you need this example

```d
unittest{
	auto matrix = slice!double(2, 5);
	matrix[] = 0;

	for(int j = 0; j < matrix.length!0; j++)
		for(int i = 0; i < matrix.length!1; i++)
			matrix[j, i] = matrix.length!1*j + i; // matrix.length!0 -> matrix.length!1

    import std.stdio;
    writeln(matrix); //  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]] !!!
}
```
