### ISSUE TITLE
Docs improvement for Slice internal representations.

### ISSUE THREAD

**Issue by tastyminerals** [libmir/mir-algorithm#237]
It would be nice to have some more information on why `Universal`, `Canonical`, `Contiguous` exist and their difference in "Internal Binary Representation" section in [Slice docs](http://mir-algorithm.libmir.org/mir_ndslice_slice.html#Slice).

Also, [this page](http://mir-algorithm.libmir.org/mir_ndslice_internal.html) is empty.

**Comment by 9il** [comment]
Agreed.
For now:
 - Contiguous: contiguous in memory (or in a user-defined iterator's field) row-major tensor, that doesn't store strides because they can be computed on the fly using lengths. The row stride is always equaled 1.
 - Canonical: has contiguous in memory (or in a user-defined iterator's field) rows of a row-major tensor, it doesn't store the strides for row dimension because it is always equaled 1. BLAS/LAPACK matrices are Canonical but originally are Column major.
 - Universal: row-major tensor, it does store the strides for all dimensions. NumPy strides are Universal.

For NumPy there is a set of articles about strides:

- https://stackoverflow.com/questions/53097952/how-to-understand-numpy-strides-for-layman
- https://www.jessicayung.com/numpy-arrays-memory-and-strides/
- https://ipython-books.github.io/46-using-stride-tricks-with-numpy/

The only difference between Universal ndslice and numpy.ndarray is that ndslice stores the strides using a count of elements to skip, while ndarray stores the value in bytes to skip (if I am not wrong).

**Comment by jmh530** [comment]
@9il I have a function below that works for `Contiguous` slices and would like to extend it to work with `Universal` and `Canonical` slices. The problem is that I don't really have a good example of `Universal` and `Canonical` slices for which the `Contiguous` version doesn't also work. Selfishly, I want to get the function working properly, but more generally I think being able to say "this slice is `Canonical` and cannot be described as `Contiguous` or `Universal`" or "this slice is `Universal` and cannot be described as `Contiguous` or `Canonical`" would be very helpful when writing whatever needs to get written for to resolve this issue.

```
DeepElementType!(Slice!(Iterator, N, kind)) at(Iterator, size_t N, SliceKind kind)(Slice!(Iterator, N, kind) slice, size_t n)
    if (kind == Contiguous)
{
    assert(n >= 0, "at: n must be greater than or equal to 0");
    assert(n < slice.elementCount, "at: n must be less than slice.elementCount");

    import mir.functional: unref;

    Iterator it = slice._iterator;
    it += n;
    return unref(*it);
}
```

**Comment by 9il** [comment]
```d
import mir.ndslice;

auto m = slice!double(5, 8); // Contiguous Matrix

auto w = m[0 .. $, 0 .. $ - 1]; // Canonocal Matrix

auto t = m.transposed; // Universal Matrix

auto f = m.front;  // Contiguous Vector

// there are no 1-D Canonical ndslices

auto d = m.diagonal; //  Universal Vector
auto c = m.front!1; //  Universal Vector
```

**Comment by 9il** [comment]
```d
import mir.ndslice;

// How to check if a slice has Contiguous strides
if (aSlice.strides == aSlice.shape.iota.strides)
{
}

// How to check if a slice has Canonical strides
if (aSlice.strides[$-1] == 1)
{
}

```

**Comment by jmh530** [comment]
@9il Thanks for that. I adapted it into the code below (as member functions of `Slice`). I have done some preliminary tests for two-dimensional slices and have not had issues yet. I plan to put together a PR once I do more tests. Hopefully I'm not missing anything obvious. 

```
    size_t valStride(size_t n)
    {
        assert(n < elementCount, "valStride: n must be less than slice.elementCount");

        static if (kind == Contiguous || N == 1) {
            return n;
        } else {
            size_t output;
            size_t remainder = n;
            size_t mul;
            foreach (i; Iota!(1, N)) //static
            {
                mul = n / _lengths[i];
                output += _strides[i - 1] * mul;
                remainder -= mul * _lengths[i];
            }
            static if (kind == Canonical) {
                output += remainder;
            } else static if (kind == Universal) {
                output += remainder * _strides[N - 1];
            }
            return output;
        }
    }

    ///
    auto ref at(size_t n) scope return @trusted
    {
        return _iterator[valStride(n)];
    }
```

**Comment by 9il** [comment]
@jmh530 You can copy past [`FlattenedIterator.getShift`](https://github.com/libmir/mir-algorithm/blob/2642999bd04e53fb49a4f4935d1eb84680ebf995/source/mir/ndslice/iterator.d#L1558-L1574)  where `_indexes` iterator field is zero vector for this case.

**Comment by jmh530** [comment]
@9il I was working on it for a few days and just got it working ([here](https://github.com/libmir/mir-algorithm/pull/273) before I saw this. I'm not entirely sure what you mean by the `_indexes` is a zero vector. It was much easier for me to get this working by calculating the indices myself.

**Comment by 9il** [comment]
FlattenedIterator has a current ND index. It computes a shift starting from this index. In your cases `_indexes` is `[0, 0, ...0]`, the current position is initial position.

**Comment by jmh530** [comment]
@9il Ah, ok. I'll try that next.
