### ISSUE TITLE
new math.stat api

### ISSUE THREAD

**Issue by 9il** [libmir/mir-algorithm#242]
- [x] `hmean` - no need special accumulator, auto extension to `double` precision . Implementation note: `.map!"1.0 / a"`
 - [x] `gmean` - needs `GMeanAccumulator` based on `Prod` instead of `Summator`. `Prod` may need to be extended.
 - [x] `median`
 - [x] var / moment ?

**Comment by jmh530** [comment]
The first thing I would want to add to that list is `median`. numir takes a sort-based approach, as does an example in mir, but a median of median approach is supposed to be faster (see [here](https://rcoh.me/posts/linear-time-median-finding/)). I could probably do a first draft on that, but you might have to take over after that. A `quantile` function would also be good, and should depend on `quickselect`, which would be similar to what is done for `median`. 

I would also add a weighted mean to the list of `gmean` and `hmean`.

I've done some work on `center`. One thing I was thinking was an average function that takes an enum for most of these different ways to get the central tendency and then is an alias to the different ones. It makes the implementation for `center` easier. `center` in numir only works for slices, but is @nogc. I tried to do another version that used `map` and would be a bit more general, but it isn't @nogc because I pass a delegate to map.

 `var`, `std`, `moment`, `skewness`, `kurtosis`, `zscore` / `scale` / `normalize` are all things that I would want to work on after `center`.

**Comment by jmh530** [comment]
I started a WIP for `median` with what is in `lubeck` as a starting point (see [here](https://github.com/jmh530/mir-algorithm/blob/b67f6f80e8f80228787a1432cf7a28c3b50aaebc/source/mir/math/stat.d#L398)). It is currently relying on std.filter, which causes a failure because something like below doesn't work. Thus, I created a separate issue to add a filter function. 
```
void main() {
    import mir.ndslice;
    import std.algorithm: filter;
    auto x = [9.0, 1, 0, 2, 3, 4, 6, 8, 7, 10, 5].sliced;
    auto y = x.chunks(5)[0].filter!(a => a < 5).length;
}
```

**Comment by 9il** [comment]
I will add the filter function. Meanwhile, we don't need the `filter` function. The link you provided has infinity type recursion if I am not wrong (it looks like it constructs `r.filter.filter.filter...` types). To make it work like in Python code you would need to allocate `filter!(...).slice`, however, it would be slow because of the number of memory allocations. Instead, the old good partitioning would work much faster and can require exactly one allocation for the whole recursion. All this looks like partial sorting.

**Comment by 9il** [comment]
> auto y = x.chunks(5)[0].filter!(a => a < 5).length;

length can't be defined for the filter result as the range primitive. Instead, the `count` function is used. Python code allocates memory, so equivalent is `... .slice.length`  or `count!(condition)`
