### ISSUE TITLE
Add `a * b` for vectors (dot product)

### ISSUE THREAD

**Issue by 9il** [libmir/mir-algorithm#91]

**Comment by jmh530** [comment]
I think you should think very carefully about this.

If you have `a*b` as dot product for vectors, then will you use matrix product/multiplication for matrices?

Consider also the Hadamard/element-wise operators in Matlab ( .*, ./, and .^). D does not have the ability to create these operators without a DIP. If you use `*` for dot product and matrix product, then it cannot be used for element-wise multiplication.

**Comment by 9il** [comment]
For element wise operations we have multidimensional `each`. Element wise operations has O_memory(f) ~ O_memory(g). For Matrix/vector-matrix/vector multiplication memory allocation size complexity is N times smaller then computational complexity. So, it make sense to add `*` (times) and `/` (solve) operations. In the same time we need reference counting matrixes and vectors because GC is not the best option for matrixes.

**Comment by jmh530** [comment]
@9il I have a few somewhat random thoughts...

My concern is with how the API will look and how it will be used in practice. I'm also interested in how quickly someone who comes from another linear algebra library will get up to speed. I don't have any particular focus on memory allocation as a means to choose what should be an operator.

I was focused on `opBinary`, whereas I would think that `each`  best corresponds to implementing `opOpAssign` (at a minimum +=, -=, *=, /=, but probably most of them). Below is an example of using `each` to return a value. It only works for `void` functions. This way causes `x` to also change, otherwise you would need to create a copy of `x`. You would instead want to use `map` instead.
```
auto add(T)(T x, T y)
{
    x.each!((ref a, b) { a += b; })(y);
    return x; //x also changes, bad
}
```

Consider Matlab's binary mathematical operators. The equivalent in D would be overloading `opBinary` for `+` as `A.map!"a+b"(B).sliced` (I haven't tested that this does what I need, but it's the basic idea) and similarly for `-`. Matlab would also overload `opBinary` for `*` as equivalent to `mtimes` in `lubeck`. This seems to be what you are suggesting, and I have no issues with that. However, they also have a `.*` for element-wise matrix multiplication. This is acknowledging the inconsistency in Matlab that `+` is element-wise, but they also want to provide some means for easily getting that same behavior. Since there is no equivalent operator in D, I would suggest that at a minimum, `mir` should have a `times` function that is equivalent to the `.*` functionality in Matlab (and similarly for divide and power). While you might argue that they are too simple, I think they will be used enough to be worth it. Consider how much simpler a long, complex mathematical function would be. Further, if a DIP ever approves additional operators, then these functions could be called by those operators. 

Many linear algebra libraries use `\` instead of `/` for solve. Armadillo and Matlab come to mind. Actually Matlab has `/`, but it is a different kind of solve, which many could find confusing. Eigen, R, and numpy survive with just solve functions.

In terms of this specific PR, you basically create a separate dot implementation. However, I have noticed that `mir-blas` and `lubeck` both have `dot` or `mtimes`. If these functions are available, I would think you would want to call them. Perhaps you can add a compile-time test for their availability?

**Comment by JohanEngelen** [comment]
@9il I think it's best not to add this. `dot(a,b)` is not much worse than `a*b`, and it is unambiguous. Note that in the title of this issue you felt the need to clarify what you mean with `a*b` ! ;-)

**Comment by 9il** [comment]
agreed

**Comment by jmh530** [comment]
@9il Nevertheless, you might create issues for opBinary and opOpAssign as future things to think about.
